#!/bin/sh
# - runtime

## nuttcp is a network performance measurement tool intended for use
## by network and system managers.

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

[ -n "$runtime" ] || runtime=300

resolve_server

log_cmd ./nuttcp -T $runtime $server
