#!/bin/bash
# - ARCH

. "$LKP_SRC/lib/reproduce-log.sh"
. "$LKP_SRC/lib/common.sh"

build_perf()
{
	local perf_dir
	perf_dir=$(ls -d /usr/src/linux-perf-*/tools/perf 2>/dev/null | head -n 1)
	[[ -n "$perf_dir" ]] || return 0

	# shellcheck disable=SC2154
	log_cmd make -j"${nr_cpu}" ARCH= -C "$perf_dir" 2>&1 || return

	[[ -f /usr/bin/perf ]] && rm -f /usr/bin/perf
	ln -s "$perf_dir"/perf /usr/bin/perf
}

build_perf || {
	parse_bool -q "$ignore_fail" && exit 0
	exit 1
}
