#!/bin/sh
# - runtime

## The program thrulay is used to measure the capacity, delay,
## and other performance metrics of a network by sending a
## bulk TCP or UDP stream over it.

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/run.sh

[ -n "$runtime" ] || runtime=300

resolve_server

prepare_exec_path

export LD_LIBRARY_PATH=/lkp/benchmarks/thrulay/lib:$LD_LIBRARY_PATH
log_cmd thrulay -t $runtime $server
