#!/bin/sh
# - interval

file=$(basename "$(dirname "$0")")
file=${file#proc-}

[ -f /proc/$file ] || exit

take_snapshot()
{
	echo time: "$(date +%s.%N)"
	cat /proc/$file
}

. $LKP_SRC/lib/wait.sh
setup_wait

monitor_snapshot_loop
