#!/usr/bin/env ruby

LKP_SRC ||= ENV['LKP_SRC'] || File.dirname(__dir__)

require 'set'
require 'timeout'
require "#{LKP_SRC}/lib/cache"
require "#{LKP_SRC}/lib/changed_stat"
require "#{LKP_SRC}/lib/constant"
require "#{LKP_SRC}/lib/lkp_git"
require "#{LKP_SRC}/lib/lkp_path"
require "#{LKP_SRC}/lib/lkp_pattern"
require "#{LKP_SRC}/lib/log"
require "#{LKP_SRC}/lib/perf_metrics"
require "#{LKP_SRC}/lib/programs"
require "#{LKP_SRC}/lib/result"
require "#{LKP_SRC}/lib/stat_bounds"
require "#{LKP_SRC}/lib/statistics"
require "#{LKP_SRC}/lib/yaml"

MARGIN_SHIFT = 5
MAX_RATIO = 5

def functional_test?(testcase)
  LKP::LinuxTestCases.instance.contain? testcase
end

def other_test?(testcase)
  LKP::OtherTestCases.instance.contain? testcase
end

def perf_metric?(name)
  LKP::PerfMetrics.instance.contain? name
end

# Check whether it looks like a reasonable performance change,
# to avoid showing unreasonable ones to humans in compare/mplot output.
def reasonable_perf_change?(name, delta, max)
  key = LKP::PerfMetricsThreshold.instance.key(name)
  unless key.nil?
    v = LKP::PerfMetricsThreshold.instance[key]
    return false if max < v
    return false if delta < v / 2 && v.instance_of?(Integer)

    return true
  end

  case name
  when /^iostat/
    return max > 1
  when /^pagetypeinfo/, /^buddyinfo/, /^slabinfo/
    return delta > 100
  when /^proc-vmstat/, /meminfo/
    return max > 1000
  when /^lock_stat/
    case name
    when 'waittime-total'
      return delta > 10_000
    when 'holdtime-total'
      return delta > 100_000
    when /time/
      return delta > 1_000
    else # rubocop:disable Lint/DuplicateBranch
      return delta > 10_000
    end
  when /^interrupts/, /^softirqs/
    return max > 10_000
  end
  true
end

# sort key for reporting all changed stats
def stat_relevance(record)
  stat = record['stat']
  relevance = if stat[0..9] == 'lock_stat.'
                5
              elsif LKP::Programs.test_prefixes.include? stat.sub(/\..*/, '.')
                100
              elsif perf_metric?(stat)
                1
              else
                10
              end
  [relevance, [record['ratio'], 5].min]
end

def sort_stats(stat_records)
  stat_records.keys.sort_by do |stat|
    order1 = 0
    order2 = 0.0
    stat_records[stat].each do |record|
      key = stat_relevance(record)
      order1 = key[0]
      order2 += key[1]
    end
    order2 /= stat_records[stat].size
    - order1 - order2
  end
end

def matrix_cols(hash_of_array)
  if hash_of_array.nil? || hash_of_array.empty?
    0
  elsif hash_of_array['stats_source']
    hash_of_array['stats_source'].size
  else
    [hash_of_array.values[0].size, hash_of_array.values[-1].size].max
  end
end

class StatClassifier
  class << self
    include Cacheable

    def function_stat?(stat)
      return false if stat.index('.time.')
      return false if stat.index('.timestamp:')
      return false if stat.index('.bootstage:')
      return true if LKP::Failure.instance.contain?(stat)
      return true if LKP::Pass.instance.contain?(stat)

      false
    end
    cache_method :function_stat?

    def latency_stat?(stat)
      LKP::IndexLatencyAll.instance.key(stat)
      false
    end
    cache_method :latency_stat?

    def failure_stat?(stat)
      LKP::Failure.instance.contain?(stat)
    end

    def pass_stat?(stat)
      LKP::Pass.instance.contain?(stat)
    end

    def memory_stat?(stat)
      LKP::MemoryStatPrefixes.instance.contain?(stat)
    end

    def bisectable_stat?(stat)
      return true if LKP::StatAllowlist.instance.contain?(stat)

      !LKP::StatDenylist.instance.contain?(stat)
    end

    KPI_STAT_DENYLIST = Set.new(['vm-scalability.stddev', 'unixbench.incomplete_result']).freeze

    def kpi_stat?(stat, _axes, _values = nil)
      return false if KPI_STAT_DENYLIST.include?(stat)

      base, _, remainder = stat.partition('.')
      LKP::Programs.all_tests_set.include?(base) && !remainder.start_with?('time.')
    end
  end
end

def add_max_latency?(stats_field)
  LKP::AddMaxLatency.instance.contain?(stats_field)
end

def sort_remove_margin(array, max_margin = nil)
  return [] if array.to_a.empty?

  margin = array.size >> MARGIN_SHIFT
  margin = [margin, max_margin].min if max_margin

  array = array.sorted
  array[margin..-margin - 1] || []
end

# NOTE: array *must* be sorted
def min_mean_max(array)
  return [0, 0, 0] if array.to_a.empty?

  [array[0], array[array.size / 2], array[-1]]
end

# Filter out data generated by incomplete run
def filter_incomplete_run(hash)
  is_incomplete_runs = hash['last_state.is_incomplete_run']
  return unless is_incomplete_runs

  delete_index_list = []
  is_incomplete_runs.each_with_index do |val, index|
    delete_index_list << index if val == 1
  end
  delete_index_list.reverse!

  hash.each_value do |v|
    delete_index_list.each do |index|
      v.delete_at(index)
    end
  end

  hash.delete 'last_state.is_incomplete_run'
end

def samples_remove_boot_fails(matrix, samples)
  perf_samples = []
  samples.each_with_index do |v, i|
    next if matrix['last_state.is_incomplete_run'] &&
            matrix['last_state.is_incomplete_run'][i] == 1

    perf_samples << v
  end
  perf_samples
end

class StatSummary
  attr_reader :sorted, :min, :mean, :max

  def initialize(array, max_margin = nil)
    @sorted = sort_remove_margin(array, max_margin)
    @min, @mean, @max = min_mean_max(@sorted)
  end

  def len
    @max - @min
  end

  def size
    @sorted.size
  end

  def empty?
    @sorted.empty?
  end
end

class StatCompare
  attr_reader :k, :a_k, :b, :options, :is_incomplete_run, :cols_a, :cols_b, :resize, :is_force_stat, :is_function_stat, :is_latency_stat

  def initialize(k, a, b, is_incomplete_run, options)
    @k = k
    @a_k = a[k]
    @b = b
    @options = options
    @is_incomplete_run = is_incomplete_run
    @cols_a = matrix_cols(a)
    @cols_b = matrix_cols(b)
    @resize = options['resize']

    @is_force_stat = options["force_#{k}"]
    @is_function_stat = StatClassifier.function_stat?(k)
    @is_latency_stat = StatClassifier.latency_stat?(k)
  end

  def process
    return if skip_stat?

    # newly added monitors don't have values to compare in the base matrix
    return unless b[k] ||
                  is_function_stat ||
                  (k =~ /^(lock_stat|perf-profile)\./ && monitored_by_b?($1))

    summary_a, summary_b = calculate_matrix_values
    return unless summary_a

    return if !is_force_stat && !changed_stats?(summary_a, summary_b)

    return if skip_critical_stat?(summary_a)

    max, x, y, z, delta, ratio = StatCompare.calc_stats_metrics(summary_a, summary_b)
    return if skip_small_change?(ratio, delta, max)

    { 'stat' => k,
      'interval' => StatCompare.format_interval(summary_a, summary_b),
      'a' => summary_a.sorted,
      'b' => summary_b.sorted,
      'ttl' => Time.now,
      'is_function_stat' => is_function_stat,
      'is_latency' => is_latency_stat,
      'ratio' => ratio,
      'delta' => delta,
      'mean_a' => summary_a.mean,
      'mean_b' => summary_b.mean,
      'x' => x,
      'y' => y,
      'z' => z,
      'min_a' => summary_a.min,
      'max_a' => summary_a.max,
      'min_b' => summary_b.min,
      'max_b' => summary_b.max,
      'max' => max,
      'nr_run' => a_k.size }
  end

  private

  def monitored_by_b?(key)
    @b_monitors ||= {}
    return @b_monitors[key] if @b_monitors.key?(key)

    @b_monitors[key] = b.keys.any? { |k| stat_key_base(k) == key }
  end

  def changed_function_stat?(a, b)
    a.max != b.max
  end

  def changed_latency_stat?(a, b)
    if options['distance']
      # auto start bisect only for big regression
      return false if b.size <= 3 && a.size <= 3
      return false if b.size <= 3 && a.min < 2 * options['distance'] * b.max
      return false if a.max < 2 * options['distance'] * b.max
      return false if a.mean < options['distance'] * b.max

      true
    elsif options['gap']
      gap?(a, b, options['gap'])
    else
      return true if a.max > 3 * b.max
      return true if b.max > 3 * a.max

      false
    end
  end

  def changed_perf_stat?(a, b)
    if options['variance']
      return true if a.len * b.mean > options['variance'] * b.len * a.mean
      return true if b.len * a.mean > options['variance'] * a.len * b.mean
    elsif options['gap']
      return true if gap?(a, b, options['gap'])
    else # options['distance']
      cs = LKP::ChangedStat.new k, a.sorted, b.sorted, options

      return true if cs.change?
    end

    false
  end

  def changed_stats?(a, b)
    if options['perf-profile'] && k =~ /^perf-profile\./ && options['perf-profile'].is_a?(a.mean.class)
      return a.mean > options['perf-profile'] ||
             b.mean > options['perf-profile']
    end

    return changed_function_stat?(a, b) if is_function_stat
    return changed_latency_stat?(a, b) if is_latency_stat

    changed_perf_stat?(a, b)
  end

  # Check if there is a significant separation between the value ranges of two datasets
  #
  # Condition for b > a (and vice versa for a > b):
  #
  #       [  Range A  ]                   [   Range B   ]
  #       |___________|                   |_____________|
  #      min         max                 min           max
  #                   <--- Gap Width --->
  #                   |                 |
  #      |           |                   |             |
  #    mean A        |                   |           mean B
  #                  |                   |
  #                  |<--- Mean Diff --->|
  #
  #    Gap Width > Mean Diff * gap_factor
  #
  def gap?(a, b, gap)
    return true if b.min > a.max && (b.min - a.max) > (b.mean - a.mean) * gap
    return true if a.min > b.max && (a.min - b.max) > (a.mean - b.mean) * gap

    false
  end

  def skip_critical_stat?(summary_a)
    return false unless (options['regression-only'] || options['all-critical']) && is_function_stat

    if summary_a.max.zero?
      options['has_boot_fix'] = true if k =~ /^dmesg\./
      return true if options['regression-only'] ||
                     (!LKP::DmesgKillPattern.instance.contain?(k) && options['all-critical'])
    end

    # this relies on the fact dmesg.* comes ahead
    # of kmsg.* in etc/default_stats.yaml
    return true if options['has_boot_fix'] && k =~ /^kmsg\./

    false
  end

  def skip_function_stat?
    return false if is_force_stat
    return false if k =~ /^(dmesg|kmsg|last_state|stderr)\./

    # if stat is packetdrill.packetdrill/gtests/net/tcp/mtu_probe/basic-v6_ipv6.fail,
    # base rt stats should contain 'packetdrill.packetdrill/gtests/net/tcp/mtu_probe/basic-v6_ipv6.pass'
    stat_base = k.sub(/\.[^.]*$/, '')
    # only consider pass and fail temporarily
    return true if k =~ /\.(error|warn|fail)$/ && !b.key?("#{stat_base}.pass")
    return true if k =~ /\.pass$/ && b.keys.none? { |stat| stat =~ /^#{stat_base}\.(error|warn|fail)$/ }

    false
  end

  def skip_regular_stat?
    # for none-failure stats field, we need asure that
    # at least one matrix has 3 samples.
    return true if !is_force_stat && cols_a < 3 && cols_b < 3 && !options['whole']

    # virtual hosts are dynamic and noisy
    return true if options['tbox_group'] =~ /^vh-/
    # VM boxes' memory stats are still good
    return true if options['tbox_group'] =~ /^vm-/ && !options['is_perf_test_vm'] && StatClassifier.memory_stat?(k)

    false
  end

  def skip_small_change?(ratio, delta, max)
    return false if is_force_stat
    return false if options['perf-profile'] && k =~ /^perf-profile\./

    return true unless ratio > 1.01 # time.elapsed_time only has 0.01s precision
    return true unless ratio > 1.05 || perf_metric?(k)
    return true unless reasonable_perf_change?(k, delta, max)

    false
  end

  def skip_stat?
    return true if a_k[-1].is_a?(String)
    return true if options['perf'] && !perf_metric?(k)
    return true if is_incomplete_run && k !~ /^(dmesg|last_state|stderr)\./
    return true if !options['more'] && !StatClassifier.bisectable_stat?(k) && !LKP::ReportAllowlist.instance.contain?(k)

    if is_function_stat
      return true if skip_function_stat?
    elsif skip_regular_stat?
      return true
    end

    false
  end

  def calculate_matrix_values
    max_margin = if is_function_stat || is_latency_stat
                   0
                 else
                   3
                 end

    b_k = b[k] || ([0] * cols_b)
    b_k << 0 while b_k.size < cols_b
    a_k << 0 while a_k.size < cols_a

    summary_b = StatSummary.new(b_k, max_margin)
    return if summary_b.empty?

    a_k.pop(a_k.size - resize) if resize && a_k.size > resize

    max_margin = 1 if b_k.size <= 3 && max_margin > 1

    summary_a = StatSummary.new(a_k, max_margin)
    return if summary_a.empty?

    [summary_a, summary_b]
  end

  class << self
    def format_interval(a, b)
      interval_a = format('[ %-10.5g - %-10.5g ]', a.min, a.max)
      interval_b = format('[ %-10.5g - %-10.5g ]', b.min, b.max)

      "#{interval_a} -- #{interval_b}"
    end

    def calc_stats_metrics(a, b)
      max = [b.max, a.max].max
      x = a.len
      z = b.len
      x = z if a.size <= 2 && x < z

      if a.mean > b.mean
        y, delta, ratio = calc_diff_metrics(a, b)
      else
        y, delta, ratio = calc_diff_metrics(b, a)
      end

      y = 0 if y.negative?
      ratio = MAX_RATIO if ratio > MAX_RATIO
      [max, x, y, z, delta, ratio]
    end

    def calc_diff_metrics(high, low)
      y = high.min - low.max
      delta = high.mean - low.mean

      ratio = MAX_RATIO
      ratio = high.mean.to_f / low.mean if low.mean.positive?

      [y, delta, ratio]
    end
  end
end

# b is the base of compare (eg. rc kernels) and normally have more samples than
# a (eg. the branch HEADs)
def __get_changed_stats(a, b, is_incomplete_run, options)
  changed_stats = {}

  (b['last_state.booting'] && !a['last_state.booting'] if options['regression-only'] || options['all-critical'])

  cols_a = matrix_cols a
  cols_b = matrix_cols b

  return if options['variance'] && (cols_a < 10 || cols_b < 10)

  b.each_key { |k| a[k] = [0] * cols_a unless a.include?(k) }

  a.each_key do |k|
    comparator = StatCompare.new(k, a, b, is_incomplete_run, options)

    changed_stat = comparator.process
    next unless changed_stat

    changed_stats[k] = changed_stat.merge(options)
    next unless options['base_matrixes']

    changed_stats[k].delete('base_matrixes')
    changed_stats[k]['extra'] ||= {}
    changed_stats[k]['extra']['base_matrixes'] = options['base_matrixes'].map { |tag, matrix| "#{tag}: #{matrix[k].inspect}" }
  end

  changed_stats
end

def load_matrices_to_compare(matrix_path1, matrix_path2, options = {})
  a = search_load_json matrix_path1
  return [nil, nil] unless a

  b = if matrix_path2
        search_load_json matrix_path2
      else
        Timeout.timeout(1800) { LKP::ChangedStat.load_base_matrix matrix_path1, a, options }
      end

  [a, b]
end

def find_changed_stats(matrix_path, options)
  changed_stats = {}

  rp = ResultPath.new
  rp.parse_result_root matrix_path

  rp.each_commit do |commit_project, commit_axis|
    next if commit_project == 'qemu'
    next if options['project'] && options['project'] != commit_project

    options['bisect_axis'] = commit_axis
    options['bisect_project'] = commit_project
    options['BAD_COMMIT'] = rp[commit_axis]

    puts options if ENV['LKP_VERBOSE']

    more_cs = get_changed_stats(matrix_path, nil, options)
    changed_stats.merge!(more_cs) if more_cs
  end

  changed_stats
end

def _get_changed_stats(a, b, options)
  is_incomplete_run = a['last_state.is_incomplete_run'] ||
                      b['last_state.is_incomplete_run']

  if is_incomplete_run && options['ignore-incomplete-run']
    changed_stats = {}
  else
    changed_stats = __get_changed_stats(a, b, is_incomplete_run, options)
    return changed_stats unless is_incomplete_run
  end

  # If reaches here, changed_stats only contains changed error ids.
  # Now remove incomplete runs to get any changed perf stats.
  filter_incomplete_run(a)
  filter_incomplete_run(b)

  is_all_incomplete_run = a['stats_source'].to_s.empty? ||
                          b['stats_source'].to_s.empty?
  return changed_stats if is_all_incomplete_run

  more_changed_stats = __get_changed_stats(a, b, false, options)
  changed_stats.merge!(more_changed_stats) if more_changed_stats

  changed_stats
end

def get_changed_stats(matrix_path1, matrix_path2 = nil, options = {})
  return find_changed_stats(matrix_path1, options) unless matrix_path2 || options['bisect_axis']

  puts <<-DEBUG if ENV['LKP_VERBOSE']
loading matrices to compare:
\t#{matrix_path1}
\t#{matrix_path2}
  DEBUG

  a, b = load_matrices_to_compare matrix_path1, matrix_path2, options
  return if a.nil? || b.nil?

  _get_changed_stats(a, b, options)
end

def add_stats_to_matrix(stats, matrix)
  return matrix unless stats

  columns = 0
  matrix.each_value { |v| columns = v.size if columns < v.size }
  stats.each do |k, v|
    matrix[k] ||= []
    matrix[k] << 0 while matrix[k].size < columns
    if v.is_a?(Array)
      matrix[k].concat v
    else
      matrix[k] << v
    end
  end
  matrix
end

def matrix_from_stats_files(stats_files, stats_field = nil, add_source: true)
  matrix = {}
  stats_files.each do |stats_file|
    stats = JSON.parse_cached stats_file
    unless stats
      log_warn "empty or non-exist stats file #{stats_file}"
      next
    end

    stats = stats.select { |k, _v| k == stats_field || k == 'stats_source' } if stats_field
    stats['stats_source'] ||= stats_file if add_source
    matrix = add_stats_to_matrix(stats, matrix)
  end
  matrix
end

def samples_fill_missing_zeros(matrix, key)
  size = matrix_cols matrix
  samples = matrix[key] || ([0] * size)
  samples << 0 while samples.size < size
  samples
end

def stat_key_base(stat)
  stat.partition('.').first
end

def strict_kpi_stat?(stat, _axes, _values = nil)
  !LKP::IndexPerfAll.instance.key(stat).nil? || !LKP::IndexLatencyAll.instance.key(stat).nil?
end

def sort_bisect_stats(stats)
  monitor_stats = LKP::Programs.all_monitors
  stats.sort_by do |stat|
    stat_name = stat[Compare::STAT_KEY]
    score = monitor_stats.include?(stat_name.split('.').first) ? -100 : 0
    key = LKP::IndexPerfAll.instance.key(stat_name)
    key ? LKP::IndexPerfAll.instance[key].to_i + score : -255 # -255 is a error value that should be less than values in index-perf-all
  end
end

def kpi_stat_direction(stat_name, stat_change_percentage)
  key_direction = nil
  key = LKP::IndexPerfAll.instance.key(stat_name)
  if key
    key_direction = LKP::IndexPerfAll.instance[key]
  else
    key = LKP::IndexLatencyAll.instance.key(stat_name)
    key_direction = LKP::IndexLatencyAll.instance[key] if key
  end

  if key_direction.nil?
    'undefined'
  elsif (key_direction * stat_change_percentage).negative?
    'regression'
  else
    'improvement'
  end
end
