#!/bin/sh
# - events
# - time
# - command
# - list_pmu_events

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/tests/pmu-tools.sh

pmu_tools_init

ocperf=$BENCHMARK_ROOT/pmu-tools/ocperf.py
[ -x "$ocperf" ] || die "Can't find pmu-tools"

ensure_pmu_events_cache

if [ -n "$list_pmu_events" ]; then
	create_links
	python "$BENCHMARK_ROOT/pmu-tools/list-events.py" >"$TMP_RESULT_ROOT/pmu-events-list"
fi

# perf may consume lots of fd
ulimit -n 102400

if [ -z "$events" ]; then
	# default event list
	events="inst_retired.any cpu_clk_unhalted.thread cpu_clk_unhalted.ref_tsc"
fi

opt_events="-e $(echo $events | sed 's/ / -e /g')"

[ "$run" = 0 ] && exit 0

$ocperf stat $opt_events --log-fd 1 true 2>&1 |
	grep 'invalid or unsupported event' &&
	exit 99

. $LKP_SRC/lib/wait.sh

[ -n "$time" ] && {
	setup_wait
	command="$WAIT_POST_TEST_CMD --timeout $time"
}

disable_nmi_watchdog

exec $ocperf stat -a --scale -I 1000 -x' ' $opt_events --log-fd 1 -- $command
