#!/bin/bash

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname "$(dirname "$(readlink -e -v "$0")")")

source $LKP_SRC/lib/result.sh
source $LKP_SRC/lib/constant.sh
source $LKP_SRC/lib/opt-date.sh

shopt -s nullglob

script_name=$(basename $0)

# Tips:
# - to search file under /result/xxx/result/ directory, use `-f result/xxx` option,like below:
#   lkp rt -d 3d -f result/0.json piglit /0/
# - to filter non-existence directory, use `-f .` option,like below:
#   lkp rt -d 3d -f . piglit  /0/
# - -d takes a day-offset spec, not just a plain count. N is a 1-indexed
#   day count: today is day 1, today-1 is day 2, etc. <, <=, >, >= clauses
#   may be comma-joined for an AND:
#     lkp rt -d3          # today, today-1, today-2         (3 days)
#     lkp rt -d'<=3'       # same as -d3                     (3 days)
#     lkp rt -d'<3'        # today, today-1                  (2 days)
#     lkp rt -d'>2'        # today-2 or older, unbounded
#     lkp rt -d'>=4'       # today-3 or older, unbounded
#     lkp rt -d'<6'        # today back through today-4      (5 days)
#     lkp rt -d'<=6'       # today back through today-5      (6 days)
#     lkp rt -d'>=4,<6'    # only today-3 and today-4
#     lkp rt -d'<=6,>3'    # today-3 through today-5
usage()
{
	cat <<-EOF
		Usage:
			lkp $script_name [-d SPEC] [-f filename] [ -p project ] [-t test_directory] [patterns...]
			  SPEC is a day-offset count N[dwm], or comma-joined <N/<=N/>N/>=N clauses
		Example:
			lkp $script_name -d 3d  lkp-ws02  xfstests /0/
			lkp $script_name -d '>=4,<6'  lkp-ws02  xfstests /0/
	EOF

	exit 1
}

[[ $# = 0 ]] && usage

while getopts "f:d:p:q:t:" opt; do
	case $opt in
	f) opt_file="$OPTARG" ;;
	d) opt_date="$OPTARG" ;;
	p) opt_project="$OPTARG" ;;
	q) opt_queue="$OPTARG" ;;
	t) opt_test_dir="$OPTARG" ;;
	?) usage >&2 ;;
	esac
done

shift $((OPTIND - 1))

[[ $opt_test_dir ]] && KTEST_PATHS_DIR=$opt_test_dir

opt_queue="$opt_queue*"

day_min=0
day_max=
[[ $opt_date ]] && read -r day_min day_max <<<"$(opt_date_to_range "$opt_date")"

if [[ $opt_date && -n $day_max ]]; then
	# bounded range: only glob the specific dates that qualify
	files=()
	for ((d = day_min; d < day_max; d++)); do
		day=$(date +%F -d "$d days ago")
		if [[ $script_name =~ ^_ ]]; then
			# shellcheck disable=SC2206
			files+=($KTEST_PATHS_DIR/$day/$day-$opt_queue $KTEST_PATHS_DIR/$day/.$day-$opt_queue)
		else
			# shellcheck disable=SC2206
			files+=($KTEST_PATHS_DIR/$day/$day-$opt_queue)
		fi
	done
else
	if [[ $script_name =~ ^_ ]]; then
		# shellcheck disable=SC2206
		files=($KTEST_PATHS_DIR/*/????-??-??-$opt_queue $KTEST_PATHS_DIR/*/.????-??-??-$opt_queue)
	else
		# shellcheck disable=SC2206
		files=($KTEST_PATHS_DIR/*/????-??-??-$opt_queue)
	fi

	if [[ $opt_date ]]; then
		# open-ended range (e.g. "-d>2" with no upper bound): keep only
		# files whose date directory is at least $day_min days old
		today_epoch=$(date +%s -d today)
		filtered=()
		for f in "${files[@]}"; do
			day=$(basename "$f")
			day=${day#.}
			day=${day:0:10}
			day_epoch=$(date +%s -d "$day" 2>/dev/null) || continue
			d=$(((today_epoch - day_epoch) / 86400))
			((d >= day_min)) && filtered+=("$f")
		done
		files=("${filtered[@]}")
	fi
fi

((${#files[@]})) || exit 0

case $opt_project in
all | ALL) projects=$(ls $LKP_SRC/repo/) ;;
"") projects="linux" ;;
*) projects=$opt_project ;;
esac

patterns="$*"

temp_file_unsort=$(mktemp /tmp/lkp-rt-unsort-XXXXXX)
temp_file_sort=$(mktemp /tmp/lkp-rt-sort-XXXXXX)

# shellcheck disable=SC2064
trap "rm -f $temp_file_unsort $temp_file_sort" EXIT

[[ $patterns ]] ||
	cat "${files[@]}" >>$temp_file_unsort

[[ $patterns ]] && {
	flag_pattern=0
	for pattern in $patterns; do
		# expand v3.12 etc. to commit SHA1
		for project in $projects; do
			pattern=$(expand_tag_to_commit $pattern $project)
		done

		if [[ "$flag_pattern" = "0" ]]; then
			cmd="grep -h -E $pattern ${files[*]}"
			flag_pattern=1
		else
			cmd="$cmd | grep -E $pattern"
		fi
	done
	eval "$cmd" >>$temp_file_unsort
}

[[ -s "$temp_file_unsort" ]] || exit 0

sed -i -e 's#/$##' $temp_file_unsort

case $script_name in
rt | ls | ll | result)
	sort $temp_file_unsort >$temp_file_sort
	;;
_rt | _result)
	awk -F'/' '{OFS="/"; NF=NF-1; print}' $temp_file_unsort | sort -u >$temp_file_sort
	;;
__rt | __result)
	awk -F'/' '{OFS="/"; NF=NF-2; print}' $temp_file_unsort | sort -u >$temp_file_sort
	;;
esac

show_one_path()
{
	case $script_name in
	ls)
		echo "$1"
		ls "$1"
		echo
		;;
	ll)
		echo "$1"
		ls -l "$1"
		echo
		;;
	*)
		echo "$1"
		;;
	esac
}

while read -r path; do
	[[ ! "$opt_file" || -e "$path/$opt_file" ]] &&
		show_one_path "$path/$opt_file"
done <$temp_file_sort

exit 0
