#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 2)

require 'optparse'
require 'ostruct'
require "#{LKP_SRC}/lib/bash"
require "#{LKP_SRC}/lib/lkp_git"
require "#{LKP_SRC}/lib/log"
require "#{LKP_SRC}/lib/result"
require "#{LKP_SRC}/lib/stats"
require "#{LKP_SRC}/lib/yaml"

options = { group: '_rt', kernel: '', field: 'time.elapsed_time', pattern: '' }

opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: lkp stat [options]'

  opts.separator ''
  opts.separator 'options:'

  opts.on('-g GROUP', '--group-by GROUP', 'group by GROUP') { |group| options[:group] = group.gsub '/', " + '/' + " }

  opts.on('-k KERNEL', '--kernel KERNEL', 'kernel branch/commit') { |kernel| options[:kernel] = kernel }

  opts.on('-p PATTERN', '--pattern PATTERN', 'grep RESULT_ROOT with PATTERN') do |pattern|
    options[:pattern] << " #{pattern}"
  end

  opts.on('-d DATE', '--date DATE', "search latest DATE days's RESULT_ROOT") do |date|
    case date
    when /[0-9]+m$/, /[0-9]+w$/, /[0-9]+d$/, /[0-9]+$/
      options[:pattern] = "  -d #{date}" + options[:pattern]
    else
      log_warn "-d #{date}: parameter is unsuitable."
      puts opts
      exit
    end
  end

  opts.on('-f FIELD', '--field FIELD', 'stats field name') { |field| options[:field] = field }

  opts.on('-r', '--raw-samples', 'show raw samples') { options[:raw] = true }

  opts.on('-q queue', '--queue queue', 'queue') { |queue| options[:pattern] = " -q #{queue}" + options[:pattern] }

  opts.on('-s', '--sort', 'sort by average value') { options[:sort] = true }

  opts.on_tail('-h', '--help', 'show this message') do
    puts opts
    exit
  end
end

opt_parser.parse!(ARGV)

unless options[:kernel].empty?
  unless Git.sha1_40?(options[:kernel])
    git = Git.open
    options[:kernel] = git.gcommit(options[:kernel]).sha
  end

  options[:pattern] << " #{options[:kernel]}"
end

_result_roots = Bash.run("#{LKP_SRC}/lkp-exec/_rt #{options[:pattern]}").split
groups = {}
_result_roots.each do |_rt|
  __rt = File.dirname _rt

  matrix_path = "#{_rt}/matrix.json"
  next unless File.size? matrix_path

  matrix = JSON.parse_cached matrix_path
  next unless matrix

  next if options[:field] !~ /last_state/ && matrix['last_state.is_incomplete_run'] && matrix['last_state.is_incomplete_run'].sum == matrix_cols(matrix)

  result_path = ResultPath.new
  result_path.parse_result_root(_rt)
  result_path['_rt'] = _rt
  result_path['__rt'] = __rt
  result_path['test'] = result_path.test_desc(/commit/, true)

  group = result_path[options[:group]]
  groups[group] ||= []

  groups[group].concat samples_fill_missing_zeros(matrix, options[:field])
end

printf "%8s %16s %16s %6s%%  %s\n", 'runs', 'sum', 'average', 'stddev', 'case'

if options[:raw]
  groups.each { |k, v| puts "#{k}: #{v}" }
else
  groups = groups.reject { |_k, v| v.sum.zero? }

  groups = groups.sort_by { |_k, v| v.reject(&:zero?).average.to_i } if options[:sort]

  groups.each do |k, v|
    v = v.reject(&:zero?) unless options[:field] =~ /last_state/
    next if v.empty?

    total = v.sum
    avg = v.average
    stddev = 100 * v.standard_deviation / v.average
    printf "%8d %16.2f %16.2f %6d%%  %s\n", v.size, total, avg, stddev, k
  end
end
