#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 2)

require 'gnuplot'
require 'optparse'
require "#{LKP_SRC}/lib/constant"
require "#{LKP_SRC}/lib/plot"
require "#{LKP_SRC}/lib/statistics"
require "#{LKP_SRC}/lib/stats"
require "#{LKP_SRC}/lib/yaml"

options = {
  output_path: 'output.png',
  x_stat_key: nil,
  x_relative: false,
  xtics: false,
  y_min: nil,
  y_relative: false,
  x_range: [nil, nil],
  diff: nil,
  diff_distance: 1,
  split_stat: nil
}

opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: mplot matrix.json stat_field [matrix.json stat_filed]... [OPTION...]'
  opts.separator ''
  opts.separator 'Example:'
  opts.separator ''

  opts.separator "mplot #{RESULT_ROOT_DIR}/fat/dd-write/1HDD-JBOD-cfq-btrfs-100dd/x86_64-rhel/matrix.json vmstat.system.in"
  opts.separator ''
  opts.separator 'options:'

  opts.on('-o FILE', '--output FILE', 'output file name') { |fn| options[:output_path] = fn }

  opts.on('-x KEY', '--x-stat-key KEY', 'x axis stat key name') { |key| options[:x_stat_key] = key }

  opts.on('-r', '--relative-x', 'x axis relative to the first element') { options[:x_relative] = true }

  opts.on('--xtics', 'draw x tics') { options[:xtics] = true }

  opts.on('--y-min YMIN', 'The y range minimum') { |ymin| options[:y_min] = ymin }

  opts.on('--relative-y', 'y axis relative to the first element') { options[:y_relative] = true }

  opts.on('--x-range RANGE', 'The x range') { |range| options[:x_range] = range.split(',').map(&:to_f) }

  opts.on('-d', '--diff', 'draw diff figure') { options[:diff] = true }

  opts.on('--diff-distance DISTANCE', 'The diff distance') { |distance| options[:diff_distance] = distance.to_i }

  opts.on('--split-stat', 'split stat to real stat and title') { options[:split_stat] = true }

  opts.on_tail('-h', '--help', 'show help message') do
    puts opts
    exit
  end
end

opt_parser.parse!(ARGV)

if ARGV.empty? || ARGV.length.odd?
  puts opt_parser
  exit
end

def apply_x_relative(matrix, x_stat_key, plotter)
  rel_x = "rel-#{x_stat_key}"
  xs = matrix[x_stat_key]
  x0 = xs.first
  matrix[rel_x] = xs.map { |xi| xi - x0 }
  plotter.set_x_stat_key(rel_x)
end

# Returns the (possibly new, matrix-augmented) stat name to plot, or nil to
# skip this matrix/stat pair when diff/y_relative is requested but the
# underlying series is missing.
def apply_y_transform(matrix, stat, options)
  if options[:diff]
    ys = matrix[stat]
    return unless ys

    diff_distance = options[:diff_distance]
    dstat = "diff#{diff_distance}-#{stat}"
    dys = (diff_distance...ys.length).map { |i| ys[i] - ys[i - diff_distance] }
    matrix[dstat] = ([0] * diff_distance) + dys
    dstat
  elsif options[:y_relative]
    ys = matrix[stat]
    return unless ys

    rstat = "rel-#{stat}"
    y0 = ys[0]
    matrix[rstat] = ys.map { |yi| yi - y0 }
    rstat
  else
    stat
  end
end

def split_stat_titles(stat, options)
  return [stat, stat] unless options[:split_stat]

  kstat, tstat = stat.split(',')
  [kstat, tstat || kstat]
end

def plot_it(matrix_stat_arr, options)
  x_stat_key = options[:x_stat_key]

  plotter = MMatrixPlotter.new
  plotter.set_x_stat_key(x_stat_key)
         .set_xtics(options[:xtics])
         .set_y_range([options[:y_min], nil])
         .set_x_range(options[:x_range])
  lines = []
  matrix_stat_arr.each_slice(2) do |matrix_fn, stat|
    matrix = JSON.parse_cached matrix_fn
    apply_x_relative(matrix, x_stat_key, plotter) if options[:x_relative]

    stat = apply_y_transform(matrix, stat, options)
    next unless stat

    kstat, tstat = split_stat_titles(stat, options)
    lines << [matrix, kstat, tstat]
  end
  plotter.set_output_file_name(options[:output_path])
         .set_lines(lines)
         .plot
end

plot_it(ARGV, options)
