suite: kbuild
testcase: kbuild
category: benchmark

runtime: 300s

nr_task:
  - 50%
  - 200%

setup-kbuild:

target: vmlinux

build_kconfig:
  - allyesconfig
  - defconfig

kbuild:

---
disk: 1HDD
fs:
  - btrfs
  - ext4
