#!/bin/sh
# - level
# - cpu
# - core
# - sleep
# - interval
# - forcecpu

# parameter interpretation:
# level: option sets the maximum level to measure.
# cpu: the number of cups.
# core: limit output to cores. Comma list of Sx-Cx-Tx.
# sleep: with XXX being the number of seconds to measure for a given time.
# interval: measure every ms instead of only once.
# --n0-desc: do not print event descriptions.

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/tests/pmu-tools.sh

pmu_tools_init

export PERF=$perf
toplev=$BENCHMARK_ROOT/pmu-tools/toplev.py
[ -x "$toplev" ] || die "Can't find pmu-tools"

ensure_pmu_events_cache

# perf may consume lots of fd
ulimit -n 102400

: "${level:=1}"
: "${sleep:=10}"
: "${interval:=100}"

set_opt()
{
	opt=
	[ -n "$cpu" ] && opt="${opt} --cpu ${cpu}"
	[ -n "$core" ] && opt="${opt} --core ${core}"
	[ -n "$forcecpu" ] && opt="${opt} --force-cpu ${forcecpu}"
}

create_links

set_opt

disable_nmi_watchdog

toplev_csv="$TMP_RESULT_ROOT"/toplev.csv
exec $toplev -l$level --no-desc $opt sleep $sleep -I $interval -x, -o $toplev_csv 2>&1
