#!/usr/bin/env ruby
LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/statistics"

workload = 0
data = false
# Capture the seven floating point variables, that are written right after
# each line that starts with "Device", like the example below

# Device tps MB_read/s MB_wrtn/s MB_dscd/s MB_read MB_wrtn MB_dscd
# nvme0n1 3366.00 136.23 0.03 0.00 3408 0 0
pattern = /^\S*\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+(\d*\.?\d+)\s+/
while (line = STDIN.gets)
  if data
    if line.match(pattern)
      puts 'tps: ' + $1
      puts 'MB_read/s: ' + $2
      puts 'MB_wrtn/s: ' + $3
      puts 'MB_dscd/s: ' + $4
      puts 'MB_read: ' + $5
      puts 'MB_wrtn: ' + $6
      puts 'MB_dscd: ' + $7
    end
    data = false
  else
    if line.match(/^Device.*$/)
      data = true
    end
  end
end
